//
// Created by Albert on 1/3/21.
//

#ifndef DESIGN_PATTERNS_C_HEADERS_STRUCTURAL_ADAPTER_MANIPULATOR_H
#define DESIGN_PATTERNS_C_HEADERS_STRUCTURAL_ADAPTER_MANIPULATOR_H

class TextManipulator {

};

#endif //DESIGN_PATTERNS_C_HEADERS_STRUCTURAL_ADAPTER_MANIPULATOR_H
