//
// Created by Albert on 1/3/21.
//

#ifndef DESIGN_PATTERNS_C_HEADERS_STRUCTURAL_ADAPTER_OBJECT_TEXTSHAP2_H
#define DESIGN_PATTERNS_C_HEADERS_STRUCTURAL_ADAPTER_OBJECT_TEXTSHAP2_H

class TextShap2 {

};

#endif //DESIGN_PATTERNS_C_HEADERS_STRUCTURAL_ADAPTER_OBJECT_TEXTSHAP2_H
