//
// Created by Albert on 1/3/21.
//

#ifndef DESIGN_PATTERNS_C_HEADERS_STRUCTURAL_ADAPTER_CLASS_TEXTSHAP_H
#define DESIGN_PATTERNS_C_HEADERS_STRUCTURAL_ADAPTER_CLASS_TEXTSHAP_H

class TextShap {

};

#endif //DESIGN_PATTERNS_C_HEADERS_STRUCTURAL_ADAPTER_CLASS_TEXTSHAP_H
